Store/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Store import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('contacts/',include('contacts.urls')),
    path('news/',include('news.urls')),
    path('testdrive/',include('testdrive.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from django.urls import path

from main import views

app_name = 'cars'
urlpatterns = [
    url('^$', views.index,name='car_list'),
    path('<int:car_id>/', views.car, name='car'),
    path('images/',views.index,name='images'),
    path('search/', views.search, name='search'),
]

main/models.py
from django.db import models
from django import forms
from django.forms import formset_factory


class Car(models.Model):
    mark = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    body = models.CharField(max_length=200)
    drive_unit = models.CharField(max_length=200)
    engine_volume = models.FloatField(max_length=10)
    content = models.TextField(default='')
    short_content = models.TextField(default='')
    img_title = models.ImageField(null=True,blank=True)
    price = models.CharField(max_length=40,default=0,null=False)
    fuel = models.CharField(max_length=40,default='')
    power = models.CharField(max_length=15,default='')
    acceleration = models.CharField(max_length=20,default='')



    def __str__(self):
        return self.model


class Photo(models.Model):
    # image = forms.ImageField(null=True,blank=True,widget=forms.FileInput(attrs={'multiple': 'multiple'}))
    image = models.ImageField(null=True,blank=True)
    cars = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='images')

main/views.py
from django.http import Http404
from django.shortcuts import render

from main.models import Car


def index(request):
    cars_list = Car.objects.order_by('engine_volume')
    return render(request,'main/index.html', {'cars_list': cars_list})


def car(request, car_id):
    try:
        car = Car.objects.get(id=car_id)
    except:
        raise Http404("Статья не найдена")

    images = car.images.order_by('id')
    return render(request, 'main/car.html', {'car': car, 'images': images})


def search(request):
    count = 0
    if request.method == 'POST':
        search_by_fuel = str(request.POST['fuel'])
        search_by_body = str(request.POST['body_car'])
        search_by_unit = str(request.POST['unit'])
        print("------------------------------------------------------------------------" + search_by_fuel)
        if search_by_fuel == 'none1' and search_by_unit == 'none1':
            my_car = Car.objects.filter(body=search_by_body).order_by('id')
            return render(request, 'main/searched.html', {'my_car': my_car})

        if search_by_fuel == 'none1' and search_by_body == 'none1':
            my_car_unit = Car.objects.filter(drive_unit=search_by_unit).order_by('id')
            return render(request, 'main/searched.html', {'my_car': my_car_unit})

        if search_by_unit == 'none1' and search_by_body == 'none1':
            my_car_fuel = Car.objects.filter(fuel=search_by_fuel).order_by('id')
            return render(request, 'main/searched.html', {'my_car': my_car_fuel})

        if search_by_fuel == 'none1':
            my_car_unit = Car.objects.filter(drive_unit=search_by_unit).order_by('id')
            my_car = Car.objects.filter(body=search_by_body).order_by('id')
            return render(request, 'main/searched.html', {'my_car': my_car,'my_car_unit':my_car_unit})

        if search_by_unit == 'none1':
            my_car_fuel = Car.objects.filter(fuel=search_by_unit).order_by('id')
            my_car = Car.objects.filter(body=search_by_body).order_by('id')
            return render(request, 'main/searched.html', {'my_car': my_car, 'my_car_fuel': my_car_fuel})

        if search_by_body == 'none1':
            my_car_fuel = Car.objects.filter(fuel=search_by_unit).order_by('id')
            my_car_unit = Car.objects.filter(drive_unit=search_by_unit).order_by('id')
            return render(request, 'main/searched.html', {'my_car_fuel': my_car_fuel,'my_car_unit':my_car_unit})

        if search_by_fuel != 'none1' and search_by_unit != 'none1' and search_by_fuel != 'none1':
            my_car = Car.objects.filter(body=search_by_body).order_by('id')
            my_car_fuel = Car.objects.filter(fuel=search_by_unit).order_by('id')
            my_car_unit = Car.objects.filter(drive_unit=search_by_unit).order_by('id')
            arr = []
            for i in Car.objects.all():
                if my_car.filter(id=i.id):
                    count += 1
                if my_car_unit.filter(id=i.id):
                    count += 1
                if my_car_fuel.filter(id=i.id):
                    count += 1
                if count == 3:
                    arr.append(i)
                count = 0

            return render(request, 'main/searched.html', {'my_car': arr})

        if search_by_fuel == 'none1' and search_by_unit == 'none1' and search_by_fuel == 'none1':
            print("------------------------------------------------------------------------"+search_by_fuel)
            cars_list = Car.objects.order_by('engine_volume')
            return render(request, 'main/index.html', {'searched_list': cars_list})

templates/main/car.html
{% extends 'mainPage.html' %}
{% block title %}Cars{% endblock %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'admin/css/slide.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/car.css' %}">
    <script src="{% static 'admin/js/script.js' %}"></script>
{% endblock %}
{% block news %}
    <div class="carcas">
        <div>
            <div class="slideshow-container">
                {% if car %}
                        {% for i in images %}
                            <div class="mySlides fade">
                                <img src="{{ i.image.url }}" style="width:100%">
                            </div>
                        {% endfor %}
                {% endif %}
            </div>
            <br>
            <div style="text-align:center">
                {% for i in images %}
                    <span class="dot"></span>
                {% endfor %}
            </div>
        </div>
        <div class="car_info">
            <h1>{{ car.mark }}  {{ car.model }}</h1>
            <p>
                {{ car.content }}
            </p>
            <h2 style="text-align: center">Характеристики</h2>
            <p>
                Привод : {{ car.drive_unit }}
            </p>
            <p>
                Кузов : {{ car.body }}
            </p>
            <p>Объем двигателя : {{ car.engine_volume}}</p>
            <p>Разгон до 100 км/ч : {{ car.acceleration}}</p>
            <p>Мощность : {{ car.power}}</p>
            <p>Топливо : {{ car.fuel}}</p>
            <em style="float: right">{{ car.price }}</em>
        </div>
    </div>


        <script>
            var slideIndex = 0;
            showSlides();

            function plusSlides(n) {
                 showSlides(slideIndex += n);
            }

            function currentSlide(n) {
                 showSlides(slideIndex = n);
            }

            function showSlides() {
              var i;
              var slides = document.getElementsByClassName("mySlides");
              var dots = document.getElementsByClassName("dot");
              for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
              }
              slideIndex++;
              if (slideIndex > slides.length) {slideIndex = 1}
              for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
              }
              slides[slideIndex-1].style.display = "block";
              dots[slideIndex-1].className += " active";
              setTimeout(showSlides,1500); // Change image every 2 seconds
            }
        </script>
{% endblock %}

templates/main/index.html
{% extends 'mainPage.html' %}
{% block title %}Cars{% endblock %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'admin/css/slide.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/body1.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="//kolesa.kz/static/frontend/css/main-common.c9bc8b6ebb.css" />
    <script src="{% static 'admin/js/script.js' %}"></script>
{% endblock %}
{% block news %}
    <div class="menu-container container mrg">
        <div class="header-menu-list ">
            <form method="post" action="{% url 'cars:search' %}">
                {% csrf_token %}
                <select class="custom-select" name="body_car">
                    <option value="none1" disabled selected style="display:none;">Кузов</option>
                    <option value="седан">седан</option>
                    <option value="купе">купе</option>
                    <option value="кроссовер">кроссовер</option>
                    <option value="хэтчбек">хэтчбек</option>
                    <option value="внедорожник">внедорожник</option>
                    <option value="лифтбэк">лифтбэк</option>
                    <option value="лимузин">лимузин</option>
                </select>
                <select class="custom-select" name="unit" style="margin-top: 10px;">
                    <option value="none1" disabled selected style="display:none;">Привод</option>
                    <option value="полный">полный</option>
                    <option value="задний">задний</option>
                    <option value="передний">передний</option>
                </select>
                <select class="custom-select dan" name="fuel">
                    <option value="none1" disabled selected style="display:none;">Топливо</option>
                    <option value="бензин">бензин</option>
                    <option value="дизель">дизель</option>
                    <option value="электричество">электричество</option>
                    <option value="газ">газ</option>
                </select>

                <div class="button forButton">
                    <input type="submit" class="btn btn-info" placeholder="Искать" value="Искать">
                </div>
            </form>
        </div>
    </div>
    <div class="cars">
        <div class="car_">
            {% if cars_list %}
                {% for cars in cars_list %}
                    <div class="personal_car">
                        <a href="{% url 'cars:car' cars.id %}">
                            {% if cars.images %}
                                <img src="{{ cars.img_title.url }}">
                            {% endif %}
                            <div class="shift">
                                <h1>
                                    {{ cars.mark }} {{ cars.model }}
                                </h1>
                                <em class="personal_car_info">
                                    {{ cars.short_content }}
                                </em>
                            </div>

                        </a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="section_">
        <canvas id="myCanvas" width="350" height="500"></canvas>
    </div>
<script>
    var canvas = document.getElementById("myCanvas");
    var ctx = canvas.getContext("2d");
    var ballRadius = 10;
    var x = canvas.width/2;
    var y = canvas.height-30;
    var dx = 2;
    var dy = -2;
    var paddleHeight = 10;
    var paddleWidth = 75;
    var paddleX = (canvas.width-paddleWidth)/2;
    var rightPressed = false;
    var leftPressed = false;
    var brickRowCount = 5;
    var brickColumnCount = 9;
    var brickWidth = 75;
    var brickHeight = 20;
    var brickPadding = 10;
    var brickOffsetTop = 30;
    var brickOffsetLeft = 30;
    var score = 0;
    var lives = 3;
    var bricks = [];
    for(var c=0; c<brickColumnCount; c++) {
        bricks[c] = [];
        for(var r=0; r<brickRowCount; r++) {
            bricks[c][r] = { x: 0, y: 0, status: 1 };
        }
    }
    document.addEventListener("keydown", keyDownHandler, false);
    document.addEventListener("keyup", keyUpHandler, false);
    document.addEventListener("mousemove", mouseMoveHandler, false);
    function keyDownHandler(e) {
        if(e.keyCode == 39) {
            rightPressed = true;
        }
        else if(e.keyCode == 37) {
            leftPressed = true;
        }
    }
    function keyUpHandler(e) {
        if(e.keyCode == 39) {
            rightPressed = false;
        }
        else if(e.keyCode == 37) {
            leftPressed = false;
        }
    }
    function mouseMoveHandler(e) {
        var relativeX = e.clientX - canvas.offsetLeft;
        if(relativeX > 0 && relativeX < canvas.width) {
            paddleX = relativeX - paddleWidth/2;
        }
    }
    function collisionDetection() {
        for(var c=0; c<brickColumnCount; c++) {
            for(var r=0; r<brickRowCount; r++) {
                var b = bricks[c][r];
                if(b.status == 1) {
                    if(x > b.x && x < b.x+brickWidth && y > b.y && y < b.y+brickHeight) {
                        dy = -dy;
                        b.status = 0;
                        score++;
                        if(score == brickRowCount*brickColumnCount) {
                            {#alert("YOU WIN, CONGRATS!");#}
                            document.location.reload();
                        }
                    }
                }
            }
        }
    }
    function drawBall() {
        ctx.beginPath();
        ctx.arc(x, y, ballRadius, 0, Math.PI*2);
        ctx.fillStyle = "#0095DD";
        ctx.fill();
        ctx.closePath();
    }
    function drawPaddle() {
        ctx.beginPath();
        ctx.rect(paddleX, canvas.height-paddleHeight, paddleWidth, paddleHeight);
        ctx.fillStyle = "#0095DD";
        ctx.fill();
        ctx.closePath();
    }
    function drawBricks() {
        for(var c=0; c<brickColumnCount; c++) {
            for(var r=0; r<brickRowCount; r++) {
                if(bricks[c][r].status == 1) {
                    var brickX = (r*(brickWidth+brickPadding))+brickOffsetLeft;
                    var brickY = (c*(brickHeight+brickPadding))+brickOffsetTop;
                    bricks[c][r].x = brickX;
                    bricks[c][r].y = brickY;
                    ctx.beginPath();
                    ctx.rect(brickX, brickY, brickWidth, brickHeight);
                    ctx.fillStyle = "#0095DD";
                    ctx.fill();
                    ctx.closePath();
                }
            }
        }
    }
    function drawScore() {
        ctx.font = "16px Arial";
        ctx.fillStyle = "#0095DD";
        ctx.fillText("Score: "+score, 8, 20);
    }
    function drawLives() {
        ctx.font = "16px Arial";
        ctx.fillStyle = "#0095DD";
        ctx.fillText("Lives: "+lives, canvas.width-65, 20);
    }
    function draw() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        drawBricks();
        drawBall();
        drawPaddle();
        drawScore();
        drawLives();
        collisionDetection();
        if(x + dx > canvas.width-ballRadius || x + dx < ballRadius) {
            dx = -dx;
        }
        if(y + dy < ballRadius) {
            dy = -dy;
        }
        else if(y + dy > canvas.height-ballRadius) {
            if(x > paddleX && x < paddleX + paddleWidth) {
                dy = -dy;
            }
            else {
                lives--;
                if(!lives) {
                    {#alert("GAME OVER");#}
                    document.location.reload();
                }
                else {
                    x = canvas.width/2;
                    y = canvas.height-30;
                    dx = 3;
                    dy = -3;
                    paddleX = (canvas.width-paddleWidth)/2;
                }
            }
        }
        if(rightPressed && paddleX < canvas.width-paddleWidth) {
            paddleX += 20;
        }
        else if(leftPressed && paddleX > 0) {
            paddleX -= 20;
        }
        x += dx;
        y += dy;
        requestAnimationFrame(draw);
    }
    draw();
</script>
{% endblock %}

templates/main/searched.html
{% extends 'mainPage.html' %}
{% block title %}Cars{% endblock %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'admin/css/slide.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/body1.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="//kolesa.kz/static/frontend/css/main-common.c9bc8b6ebb.css" />
    <script src="{% static 'admin/js/script.js' %}"></script>
{% endblock %}
{% block news %}
    <div class="cars">
        <div class="car_ caaar">
            {% if my_car %}
                {% for cars in my_car %}
                    <div class="personal_car">
                        <a href="{% url 'cars:search' %}">
                            {% if cars.images %}
                                <img src="{{ cars.img_title.url }}">
                            {% endif %}
                            <div class="shift">
                                <a href="{% url 'cars:car' cars.id %}">
                                <h1>
                                    {{ cars.mark }} {{ cars.model }}
                                </h1>
                                <em class="personal_car_info">
                                    {{ cars.short_content }}
                                </em>
                                </a>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            {% elif my_car and my_car_unit and my_car_fuel %}
                {% for cars in my_car %}
                    <div class="personal_car">
                        <a href="{% url 'cars:search' %}">
                            {% if cars.images %}
                                <img src="{{ cars.img_title.url }}">
                            {% endif %}
                            <div class="shift">
                                <a href="{% url 'cars:car' cars.id %}">
                                <h1>
                                    {{ cars.mark }} {{ cars.model }}
                                </h1>
                                <em class="personal_car_info">
                                    {{ cars.short_content }}
                                </em>
                                </a>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            {% endif %}

        </div>
    </div>
{#    <div class="cars search_car">#}
{#        <div class="car_" >#}
{#            {% if my_car_unit %}#}
{#                {% for cars in my_car_unit %}#}
{#                    <div class="personal_car">#}
{#                        <a href="{% url 'cars:search'%}">#}
{#                            {% if cars.images %}#}
{#                                <img src="{{ cars.img_title.url }}">#}
{#                            {% endif %}#}
{#                            <div class="">#}
{#                                <h1>#}
{#                                    {{ cars.mark }} {{ cars.model }}#}
{#                                </h1>#}
{#                                <em class="personal_car_info">#}
{#                                    {{ cars.short_content }}#}
{#                                </em>#}
{#                            </div>#}
{#                        </a>#}
{#                    </div>#}
{#                {% endfor %}#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{% endblock %}