Store/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Store import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('contacts/',include('contacts.urls')),
    path('news/',include('news.urls')),
    path('testdrive/',include('testdrive.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from django.urls import path

from main import views

app_name = 'cars'
urlpatterns = [
    url('^$', views.index,name='car_list'),
    path('<int:car_id>/', views.car, name='car'),
    path('images/',views.index,name='images'),
    path('search/', views.search, name='search'),
]

news/urls.py
from django.urls import path
from django.conf.urls import url,include

from . import views
from django.conf.urls.static import static
from django.views.generic import ListView,DetailView
from django.db import models
from .models import Article,Comment


app_name='newsApp'
urlpatterns = [
    # url(r'^$',ListView.as_view(queryset=Article.objects.all(),template_name="../templates/newsApp/posts.html"))
    url('^$', views.index,name='latest_articles_list'),
    path('<int:article_id>/',views.detail,name='detail'),
    path('<int:article_id>/leave_comment',views.leave_comment,name='leave_comment'),
]

news/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.utils.timezone import now


class Article(models.Model):
    article_title = models.CharField(max_length=200)
    article_content = RichTextUploadingField()
    article_img = models.ImageField(null=True,blank=True)
    pub_date = models.DateTimeField(null=True,default=now)
    article_short_content = models.TextField(max_length=300)

    def __str__(self):
        return self.article_title

    class Meta:
        verbose_name='Статья'
        verbose_name_plural ='Статьи'


class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE)
    author_name = models.CharField('имя автора',max_length=50)
    comment_text = models.CharField('текст комментария',max_length=200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name='Комментарий'
        verbose_name_plural='Комментарии'

news/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from .models import Article,Comment
from django.urls import reverse
import requests
from bs4 import BeautifulSoup as BS
def index(request):
    latest_articles_list=Article.objects.order_by('-pub_date')[:7]
    return render(request,'news/posts.html',{'latest_articles_list':latest_articles_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена")

    latest_comment_list=a.comment_set.order_by('-id')[:20]
    return render(request,'news/details.html', {'article': a,'latest_comment_list': latest_comment_list})


def leave_comment(request, article_id):
    try:
        a=Article.objects.get(id=article_id)
    except:
        raise Http404("Статься не найдена")

    a.comment_set.create(author_name=request.POST['name'],comment_text=request.POST['text'])
    return HttpResponseRedirect(reverse('newsApp:detail',args=(a.id,)))

templates/news/details.html
{% extends 'mainPage.html' %}

{% block title %}{{ article.article_title }}{% endblock %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'admin/css/news.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/details.css' %}">
{% endblock %}
{% block news %}
     {% if article.article_img %}
        <img id="img__news"  src="{{ article.article_img }}" width="200px" height="200px">
     {% endif %}
    <div class="new-1-detail ang">
        <h2>{{ article.article_title }}</h2>
        <div class="">
            <p>{{ article.article_content }}</p>
        </div>
            <em class="">{{ article.pub_date }}</em>
    </div>

    <div class="comments__">
        <div class="">

            <form action="{% url 'newsApp:leave_comment' article.id %}" method="post">
                {% csrf_token %}

                <input type="text" required="" class="form-control" placeholder="Ваше имя" name="name"><br>
                <textarea name="text" class="form-control" required="" placeholder="Текст комментария" cols="5" rows="3"></textarea><br>

                <button type="submit" class="btn btn-info" >Оставить комментарий</button>
            </form>

        </div>
    </div>
    <h3 class="title-comments">Комментарии</h3>
    {% if latest_comment_list %}
            {% for c in latest_comment_list %}
    <div class="">
    <div class="comments ">
        <ul class="media-list underline">
            <!-- Комментарий (уровень 1) -->
            <li class="media">
                <div class="media-body border p-3">
                    {% if c.author_name and c.comment_text %}
                    <div class="media-heading">

                        <div class="author"><h3><i>{{ c.author_name }}</i></h3></div>

                    </div>

                    <div class="media-text text-justify">{{ c.comment_text }}
                    </div>
                    {% else %}
                        <footer style="margin-top: 500px"></footer>
                    {% endif %}
                </div>
            </li>
            <!-- Конец комментария (уровень 1) -->
        </ul>
    </div>
    {% endfor %}
    {% endif %}
    </div>
    <script>
        var d = new Date();
        var months = ["January","February","March","April","May","June","July","August","September","October","November","December"];
        document.getElementById("demo").innerHTML = d.getDate()+' '+months[d.getMonth()]+','+d.getFullYear();
    </script>
{% endblock %}

templates/news/posts.html
{% extends 'mainPage.html' %}

{% block title %}Новости{% endblock %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'admin/css/news.css' %}">
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{% endblock %}
{% block news %}
    <div class="for-news">

            {% if latest_articles_list %}
                {% for i in latest_articles_list %}
                    <div class="new-1">
                        <h3>{{i.article_title}}</h3>
                        {% if i.article_img %}
                            <img class="img___" src="{{ i.article_img }}" width="150px" height="100px">
                        {% endif %}
                        <p>
                            {{i.pub_date}}
                            <br>
                            {{ i.article_short_content }}
                            <br>
                            <a href="{% url 'newsApp:detail' i.id %}" class="a-new">
                                <strong>Читать подробнее...</strong>
                            </a>
                        </p>
                    </div>
                {% endfor %}
            {% else %}
                <p style="color: white; margin-top: 40px; font-size: 48px; ">Статьи не найдены</p>
             {% endif %}

    </div>

{% endblock %}