Store/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Store import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('contacts/',include('contacts.urls')),
    path('news/',include('news.urls')),
    path('testdrive/',include('testdrive.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from django.urls import path

from main import views

app_name = 'cars'
urlpatterns = [
    url('^$', views.index,name='car_list'),
    path('<int:car_id>/', views.car, name='car'),
    path('images/',views.index,name='images'),
    path('search/', views.search, name='search'),
]

testdrive/urls.py
from sys import path

from django.conf.urls import url

from testdrive import views


app_name = 'test-drive'
urlpatterns = [
    url('^$', views.index),
    url('add_test-drive',views.add_testdrive,name='add_test-drive'),
]

testdrive/models.py
from django.db import models
from django.utils.timezone import now


class Testdrive(models.Model):
    male = models.CharField(max_length=10, null=False,default='male')
    name = models.CharField(max_length=30, null=False,default='')
    surname = models.CharField(max_length=30, null=False,default='')
    patronymic = models.CharField(max_length=30 , null=True)
    phone = models.CharField(max_length=12, null=False,default='')
    email = models.EmailField(null=True)
    mark = models.CharField(max_length=50, null=True,default='')
    model = models.CharField(max_length=50, null=False,default='Выберите модель')

    def __str__(self):
        return self.email

testdrive/views.py
from django.shortcuts import render, redirect

from django.core.mail import send_mail
from django.conf import settings

from testdrive.models import Testdrive


def index(request):
    return render(request,'testdrive/test-drive.html')


def add_testdrive(request):
    if request.method == 'POST':
        male = request.POST['male']
        name = request.POST['name']
        surname = request.POST['surname']
        patronymic = request.POST['patronymic']
        phone = request.POST['phone']
        email = request.POST['email']
        # mark = request.POST['mark']
        model = request.POST['model']
        Testdrive.objects.create(male=male, name=name, surname=surname, patronymic=patronymic,
                                 phone=phone, email=email, model=model)
        if email:
            subject = 'Тест-драйв'
            message = ' Спасибо за запись на тест-драйв,мы свяжемся с вами в ближайшее время. '
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [email,]
            send_mail(subject, message, email_from, recipient_list)

    return render(request, 'testdrive/test-drive.html')

templates/testdrive/test-drive.html
{% extends 'mainPage.html' %}

{% block title %}Новости{% endblock %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'admin/css/news.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/test-drive.css' %}">
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{% endblock %}
{% block news %}
    <div class="form" name="forma">
                <div>
                    <h3><p style="margin-left:30px;margin-top: 10px;">Запись на тест-драйв</p></h3>
                </div>
                <div class="text-right">
                    <small>Поля, отмеченные знаком *, обязательны для заполнения</small>
                </div>
                <br>
                <form action="{% url 'test-drive:add_test-drive' %}" method="post">
                    {% csrf_token %}
                    <div>
                        <div>
                            <h4>Персональные данные</h4>
                        </div>
                        <div class="personal-data1">
                            <h5 style="margin-left:50px;">Обращение*</h5>
                            <label ><input type="radio"  value="male" name="male" checked> Господин</label>
                            <label ><input type="radio" value="female" name="male"> Госпожа</label>
                        </div>
                        <div class="personal-data2">
                                <h5 style="margin-left:100px;">Ф.И.О.*</h5>
                                <label><input class="personal-data form-control" name="surname" placeholder="Фамилия*" type="text" required></label>
                                <label><input class="personal-data form-control"  name="name" placeholder="Имя*" type="text" required></label>
                                <label><input class="personal-data form-control"  name="patronymic" placeholder="Отчество" type="text"></label>
                        </div>
                        <div class="personal-data3">
                                <h5 style="margin-left: 20px;">Способы связи*</h5>
                                <label><input class="personal-data form-control" name="phone" placeholder="Телефон*" required></label>
                                <label><input type="email" class="personal-data form-control" name="email" placeholder="Email" required></label>
                        </div>
                    </div>
                    <br>
                    <div>
                        <div>
                            <h4>Запись на тест-драйв</h4>
                        </div>
                        <br>
                        <div class="test-drive1">
                            <h5 style="margin-left: 50px;">Выбор модели*</h5>
                            <label>
                                <select name="model" class="custom-select mb-3" required>
                                    <option value="" disabled selected style="display:none;">Выберите модель</option>
                                    <optgroup label="BMW">
                                            <option value="x5">X5</option>
                                            <option value="m6">M6</option>
                                        <option value="i8">i8</option>
                                    </optgroup>
                                    <optgroup label="Mercedes-Benz">
                                        <option value="S500">S 500</option>
                                        <option value="E550">E 550</option>
                                        <option value="G63AMG">G 63 AMG</option>
                                    </optgroup>
                                    <optgroup label="Tesla">
                                        <option value="ModelS">Model S</option>
                                        <option value="ModelX">Model X</option>
                                        <option value="Model3">Model 3</option>
                                    </optgroup>
                                    <optgroup label="Toyota">
                                        <option value="Camry">Camry</option>
                                        <option value="LandCruiser">Land Cruiser</option>
                                        <option value="Corolla">Corolla</option>
                                    </optgroup>
                                    <optgroup label="Lexus">
                                        <option value="RX330">RX 330</option>
                                        <option value="LX570">LX 570</option>
                                        <option value="GS300">GS 300</option>
                                    </optgroup>
                                </select>
                            </label>
                        </div>
                    </div>
                    <br>
                    <div>
                        <div>
                            <h4>Информация о защите персональных данных</h4>
                        </div>
                        <br>
                        <div class="protect-data">
                            <h5 style="margin-left: 45px;">Отметка о согласии*</h5>
                            <label class="protect" style="text-align: center;">
                                <input type="checkbox" class="" required>Я внимательно ознакомился и соглашаюсь с условиями обработки
                                моих персональных данных, а также я подтверждаю наличие согласия субъектов иных указанных
                                мной персональных данных с условиями их обработки.
                            </label>
                        </div>
                    </div>
                    <div class="submit-btn">
                        <input class="submit btn btn-secondary" type="submit">
                    <script>alert(Спасибо)</script>
                    </div>
                </form>
        </div>

{% endblock %}