Store/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Store import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('contacts/',include('contacts.urls')),
    path('news/',include('news.urls')),
    path('testdrive/',include('testdrive.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.conf.urls import url
from django.urls import path

import contacts
from contacts import views

app_name = 'contacts'
urlpatterns = [
    url('^$', views.index),
    path(r'leave_feedback',views.leave_feedback,name='leave_feedback'),
]

main/urls.py
from django.conf.urls import url
from django.urls import path

from main import views

app_name = 'cars'
urlpatterns = [
    url('^$', views.index,name='car_list'),
    path('<int:car_id>/', views.car, name='car'),
    path('images/',views.index,name='images'),
    path('search/', views.search, name='search'),
]

contacts/models.py
from django.db import models

class Contacts(models.Model):
    Firstname = models.CharField(max_length=200)
    Lastname = models.CharField(max_length=200)
    Email = models.EmailField()
    Phone = models.CharField(max_length=200)
    Comment = models.TextField()

    def __str__(self):
        return self.Email

    class Meta:
        verbose_name='Контакт'
        verbose_name_plural='Контакты'

contacts/views.py
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from contacts.models import Contacts


def index(request):
    return render(request,'contacts/contacts.html',)

def leave_feedback(request):
    Contacts.objects.create(Firstname=request.POST['firstname'],Lastname=request.POST['lastname'],
                            Email=request.POST['email'],Phone=request.POST['contacts'],Comment=request.POST['text'])
    return render(request,'contacts/contacts.html')

templates/contacts/contacts.html
{% extends 'mainPage.html' %}
{% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'admin/css/contacts.css' %}">
{% endblock %}
{% block news %}
    <div class="map">
        <div class="map1">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d22919.381879699926!2d76.91167841235458!3d43.
            238970940425446!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x2426740f56437e63!2z0JzQtdC20LTRg9C90LDRgNC-0LTQvdGL0Lkg0YPQvdC40LLQtdGA0YHQuNGC0LXRgiDQuNC90YTQvtGA0LzQsNGG0LjQvtC90L3Ri9GFINGC0LXRhdC90L7Qu9C-0LPQuNC5!5e0!3m2!1sru!2skz!4v1575264796283!5m2!1sru!2skz"
                    width="800" height="450" frameborder="0" style="border:4px;" allowfullscreen=""></iframe>
        </div>
    </div>
    <div class="form">
        <div>
            <form action="{% url 'contacts:leave_feedback' %}" method="post">
                {% csrf_token %}
                <div class="names">
                    <label>Firstname <input class="form-control" type="text" name="firstname"></label>
                    <label>Lastname <input class="form-control" type="text" name="lastname"></label>
                </div>
                <div class="contacts">
                    <label>Email <input class="form-control" type="text" name="email"></label>
                    <label>Phone <input class="form-control" type="number" name="contacts"></label>
                </div>
                <div class="comments">
                    <p style="color: black">Comment</p>
                    <textarea name="text" OnKeyUp="ResizeTextArea(this,2);" class="form-control" cols="20" rows="2"></textarea>
                </div>

                <div class="submit">
                    <input class="submit btn-danger" type="submit">
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript">
// функция подсчета количества строк
    function countLines(strtocount, cols) {
	var hard_lines = 1;
	var last = 0;
	while ( true ) {
		last = strtocount.indexOf("\n", last+1);
		hard_lines ++;
		/* if ( hard_lines == 35) break; */
		if ( last == -1 ) break;
		}
	var soft_lines = Math.ceil(strtocount.length / (cols-1));
	var hard = eval("hard_lines " + unescape("%3e") + "soft_lines;");
	if ( hard ) soft_lines = hard_lines;
	return soft_lines;
    }
    function ResizeTextArea(the_form,min_rows) {
        the_form.rows = Math.max(min_rows,countLines(the_form.value,the_form.cols) +1);
    }
    </Script>
{% endblock %}
                    